version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: MottuGridDb
      MYSQL_USER: user_test
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"    # Mapeia a porta 3306 do container para a porta 3306 do host
    volumes:
      - mysql_data:/var/lib/mysql  # Persistência de dados
    networks:
      - test_network

volumes:
  mysql_data:

networks:
  test_network:
    driver: bridge
